language: python
python:
  - "2.7"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
  matrix:
    - TOX_ENV=py26-dj16,
    - TOX_ENV=py27-dj16,
    - TOX_ENV=py27-dj17,
    - TOX_ENV=py27-dj18,
    - TOX_ENV=py27-dj19,
    - TOX_ENV=py27-dj110,
    - TOX_ENV=py27-dj111,
    - TOX_ENV=py33-dj16,
    - TOX_ENV=py33-dj17,
    - TOX_ENV=py33-dj18,
    - TOX_ENV=py33-dj19,
    - TOX_ENV=py33-dj110,
    - TOX_ENV=py33-dj111,
    - TOX_ENV=py34-dj17,
    - TOX_ENV=py34-dj18,
    - TOX_ENV=py34-dj19,
    - TOX_ENV=py34-dj110,
    - TOX_ENV=py34-dj111,
    - TOX_ENV=py35-dj17,
    - TOX_ENV=py35-dj18,
    - TOX_ENV=py35-dj19,
    - TOX_ENV=py35-dj110,
    - TOX_ENV=py35-dj111,
    - TOX_ENV=flake8
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
